services:
  backend:
    build: .
    command: gunicorn app:app --bind 0.0.0.0:10000 --workers 1 --reload
    ports:
      - "5000:10000"
    # Add a reliable DNS server to prevent network resolution issues inside the container
    dns:
      - 8.8.8.8
    volumes:
      - .:/app # Mount local code for development
      - venv:/app/venv # Persist the virtual environment in a named volume
    env_file:
      - .env
    environment:
      - FLASK_ENV=development

# Define the named volume
volumes:
  venv: