services:
  - type: web
    name: stock-dashboard
    region: oregon
    plan: free
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "chmod +x start.sh && ./start.sh"
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.4"
      - key: REDIS_HOST
        fromService:
          type: redis
          name: fintra-redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: fintra-redis
          property: port
      - key: REDIS_PASSWORD
        fromService:
          type: redis
          name: fintra-redis
          property: password

  - type: redis
    name: fintra-redis
    region: oregon
    plan: free
    ipAllowList: []  # Required for private services
