services:
  - type: web
    name: stock-dashboard
    plan: free
    runtime: docker
    region: oregon
    dockerfilePath: ./Dockerfile
    startCommand: gunicorn app:app --bind 0.0.0.0:10000 --workers 3
